 services:
  app:
    image: 'ermc:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - oracle-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@//localhost:11521/ORCLPDB1
      - SPRING_DATASOURCE_USERNAME=ORCLPDB1
      - SPRING_DATASOURCE_PASSWORD=Oracle_123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  oracle-db:
    image: container-registry.oracle.com/database/express:latest
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=Oracle_123
    ports:
      - 1521:1521
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/Oracle_123@//localhost:1521/ORCLCDB as sysdba", "@healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  oracle-data:
  oracle-backup: