spring:
  application:
    name: ermc-back
# This is only temporary -> will migrate to Oracle SQL later on
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  file:
    name: logs/app.logs
    path: logs
application:
  security:
    jwt:
      secret-key: 556A586E3272357538782F413F4428472B4B6250655368566B59703373367639
      expiration: 86400000
      refresh-token:
        expiration: 2592000000