spring:
  application:
    name: ermc-back
# This is only temporary -> will migrate to Oracle SQL later on
  datasource:
    url: jdbc:postgresql://localhost:5432/ermc
    username: postgres
    password: postgres
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.OracleDialect
logging:
  file:
    name: logs/app.logs
    path: logs
application:
  security:
    jwt:
      secret-key: 556A586E3272357538782F413F4428472B4B6250655368566B59703373367639
      expiration: 86400000
      refresh-token:
        expiration: 2592000000
pdf:
  directory: reports/
  file-name: employee-report
  company-logo: src/main/resources/static/logo.jpeg