package com.erms.model;/*
 * Employee Records Management System Service
 * Centralized Employee Management
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



import lombok.*;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;
import java.io.IOException;
/**
 * ApiError
 */
@Builder
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class ApiError {

  private String status;
  private LocalDateTime timestamp;
  private String message;
  private String debugMessage;
  private List<Object> subErrors;

}
